### ISSUE TITLE
Username does not exist

### ISSUE THREAD

**Issue by sugo512** [emoncms/backup#2]
Doing a restore on a non-pi emoncms Ubuntu install. Import database seems fine, but can't login or register.

**Comment by sugo512** [comment]
Nevermind - wrong user.  Anyway, backup/restore scripts work with a little modifications on a non-pi system too.

**Comment by Paul-Reed** [comment]
What modification? Is there a bug?

**Comment by sugo512** [comment]
No - not a bug. If the emoncms install is not on a pi, then a lot of the directories are different. A few path changes and the restore works fine.

**Comment by Paul-Reed** [comment]
Ok, thanks.
