### ISSUE TITLE
Sidebar compatiablity 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/backup#29]
The Backup module needs sidebar compatible menu added. The backup module has it's own sidebar menu to switch between Export / Import pages.

**Comment by emrysr** [comment]
I've added a tabs interface to jump between Export & Import

**Comment by glynhudson** [comment]
![Screenshot 2019-04-30 at 17 35 27](https://user-images.githubusercontent.com/758844/56978611-cd373500-6b6f-11e9-9641-0d05003e78bc.png)
