### ISSUE TITLE
Backup on different enviroments like Ubuntu 

### ISSUE THREAD

**Issue by robertsLando** [emoncms/backup#3]
This module only works with emonpi, is there a working version for Ubuntu?

**Comment by Paul-Reed** [comment]
Daniel, no, it would need further development to work with self-builds.
There are other options though; if you are running node-red you could try [backing up to dropbox](https://community.openenergymonitor.org/t/node-red-flow-for-archiving-to-dropbox/5293), or if not [this alternative version](https://github.com/Paul-Reed/dropbox-archive).

Paul

**Comment by Paul-Reed** [comment]
Closed - no further comment received.
