### ISSUE TITLE
Location of config file is inconsistent

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#33]
https://github.com/emoncms/backup/blob/a1e7cb59d647ccdd89a78b6ba5781b5397b1d709/backup-module/backup_controller.php#L24

With the module install location moving.  This is no longer guaranteed to be correct.  However, during transition it cannot simply be changed, two checks will be required one for each possible location.

The export script, looks for the config in the new location.
https://github.com/emoncms/backup/blob/f7530698bdfc5facc90e23142fbcea548c0b0f23/emoncms-export.sh#L2

**Comment by TrystanLea** [comment]
i think these might be fine? not sure that im following the issue, or perhaps we resolved this one already?

**Comment by borpin** [comment]
That long since I raised it I'm not remembering why. 

I think the problem may surface where an old `settings.php` with `$homedir` defined is migrated to the new setup and does not find the config file.

AFAICS, `$homedir` has been removed?

**Comment by TrystanLea** [comment]
> AFAICS, $homedir has been removed?

Yes, this looks to be fixed now. Thanks
