### ISSUE TITLE
hash symbols in config.cfg causing an error

### ISSUE THREAD

**Issue by pb66** [emoncms/backup#38]
ref https://community.openenergymonitor.org/t/permanent-raspberry-pi-booting-after-failed-emonpi-update/10963/22?u=pb66 and https://www.php.net/manual/en/function.parse-ini-file.php

Originally I submitted PR #37  to swap out the hashes for semi-colons but that caused and issue for the bash script so I closed it again.

Note that reading the parse_ini_file() changelog the use of hashes should effect php7.0 users, but as it turns out, the linked case is a php5.6 setup ????

**Comment by TrystanLea** [comment]
Same issue: https://community.openenergymonitor.org/t/backup-module-comments-starting-with-deprecated/13172/4

**Comment by TrystanLea** [comment]
I've implemented a fix for this that filters out all lines that start with a #:
https://github.com/emoncms/backup/commit/87791bc9faa959d173ee136a7cebe7a33fe011fe
