### ISSUE TITLE
non-default backup destination not working

### ISSUE THREAD

**Issue by danbates2** [emoncms/backup#40]
the problem is that the ~/data directory is getting full of daily backup files.

It'd be tidy if the default backup location for the backup was another directory within ~/backup

for example I have ~/backup/backups made

but when I set it in config.cfg I get this error:

![Screen Shot 2019-07-20 at 11 19 26](https://user-images.githubusercontent.com/5250782/61577515-51021d00-aae0-11e9-9d22-55e398370901.png)

**Comment by borpin** [comment]
> for example I have ~/backup/backups made
> 
> but when I set it in config.cfg I get this error:

Do you use the full path i.e `/home/pi/data/backup/backups/`?

**Comment by danbates2** [comment]
That worked, easy.
