### ISSUE TITLE
Backup still points to the mqtt_input service

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#41]
https://github.com/emoncms/backup/blob/8a0f0afaf911a80fce5e67ea65dc0dcff9002a4f/emoncms-import.sh#L28

I think this should be changed to `emoncms_mqtt`

**Comment by TrystanLea** [comment]
thanks @borpin added: https://github.com/emoncms/backup/commit/8386dd07d2786cbab0c42a184d5022f8b21757cd

**Comment by borpin** [comment]
Ah, I wonder if it actually need to check for both to allow for systems that may still be running the old version?  This is the backup script after all 😁
