### ISSUE TITLE
Use drop-in to modify php configuration

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#42]
https://github.com/emoncms/backup/blob/8a0f0afaf911a80fce5e67ea65dc0dcff9002a4f/install.sh#L22-l26

Ref https://community.openenergymonitor.org/t/permanent-raspberry-pi-booting-after-failed-emonpi-update/10963/27

This has some discussion about modifying php.ini bu drop-in rather than changing the master file. As I think the Vhost mechanism has been enabled, this could probably be done an just the vhost.

**Comment by borpin** [comment]
Suggest

```
cat << EOF |
post_max_size = 3G
upload_max_filesize = 3G
upload_tmp_dir = ${upload_dir}
upload_tmp_dir = ${upload_dir}
EOF
sudo tee /etc/php/$PHP_VER/mods-available/10-emoncmsbackup.ini

sudo phpenmod emoncmsbackup
```

**Comment by TrystanLea** [comment]
thanks @borpin

**Comment by TrystanLea** [comment]
tested basic operation of mods-available file creation but not the application of the settings itself so far
https://github.com/emoncms/backup/commit/21cefffd3c0ebf4f7249c21c108cb889c1a23ea3

**Comment by TrystanLea** [comment]
Merged into master :)
