### ISSUE TITLE
Variable $emoncms_nodes_service is never set.

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#45]
https://github.com/emoncms/backup/blob/8a0f0afaf911a80fce5e67ea65dc0dcff9002a4f/emoncms-import.sh#L113

This variable is checked but has never been set.

**Comment by TrystanLea** [comment]
removed thanks https://github.com/emoncms/backup/commit/3e73db57a0b5aa26e47a613bf92e7a48d1a16a6b
