### ISSUE TITLE
Setting do not work on systems that are not upto date

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#48]
https://github.com/emoncms/backup/blob/5afedb350feec160d54c1baf32f37684690f11d0/get_emoncms_mysql_auth.php#L31-L31

If someone is trying to do a manual backup on migration this will not work.

Check for presence of a `ini` file in the root folder I suggest.

**Comment by TrystanLea** [comment]
I think it should work if they have a recent version of emoncms core, if they are doing a manual backup on an older system their backup module and emoncms core should also be an older variant?

**Comment by borpin** [comment]
There were a number of issues with this reported on the forum where the user was not able to get the authorisation.

https://community.openenergymonitor.org/t/lcd-screen-says-updating-do-not-unplug-updating-system-from-v8-5/12191/8?u=borpin

**Comment by TrystanLea** [comment]
Hello @borpin reading through the thread and noting your summary:

> The key points I think are;
> 
>     Use the right (old) backup module and do a manual export.
>     Add MQTT user/password to emonhub.cfg and or use default.
> 
> Anything else?

Now that we have it, I think we should try the USB import method first for users importing from very old images.

The emonhub.conf issue might still persist though as the old version may well be copied. Sounds like something we need to keep an eye out for and perhaps add to the guide?

**Comment by borpin** [comment]
That only solves the migration if a system, not the backing up of an older system. It also assumes that it is running on an SDcard. Yes that covers 95% of user base, but not everyone.
