### ISSUE TITLE
Backup not possible

### ISSUE THREAD

**Issue by heebtob** [emoncms/backup#49]
When I try to create a backup via GUI, it shows me the following error: Segmentation fault.
Is there a way to fix this?

<details><summary>Server Information</summary>

# Server Information
## Services
 
- **emonhub** :- **Active** Running
- **emoncms_mqtt** :- **Active** Running
- **feedwriter** :- **Active** Running - sleep 60s 49 feed points pending write
- **service-runner** :- **Active** Running
- **emonPiLCD** :- **Active** Exited
- **redis-server** :- **Active** Running
- **mosquitto** :- **Active** Running

## Emoncms
 
- **Version** :- low-write 10.1.5
- **Modules** :- Administration | App v2.0.3 | Backup v2.1.1 | EmonHub Config v2.0.3 | Dashboard v2.0.4 | Device v2.0.1 | EventProcesses | Feed | Graph v2.0.3 | Input | Postprocess v2.1.0 | CoreProcess | Schedule | Network Setup v1.0.0 | sync | Time | User | Visualisation | WiFi v2.0.1
- **Git** :- 
     - **URL** :- https://github.com/emoncms/emoncms.git
     - **Branch** :- * stable
     - **Describe** :- v9.5.1-2216-gd2079459

## Server
 
- **OS** :- Linux 4.14.71-v7+
- **Host** :- emonpi | emonpi | (10.11.120.190)
- **Date** :- 2019-11-03 22:37:00 UTC
- **Uptime** :- 22:37:00 up 70 days, 10:47,  0 users,  load average: 0.14, 0.15, 0.10

## Memory
 
- **RAM** :- Used: 27.22%
    - **Total** :- 976.74 MB
     - **Used** :- 265.9 MB
     - **Free** :- 710.84 MB
- **Swap** :- Used: 0.25%
    - **Total** :- 100 MB
     - **Used** :- 256 KB
     - **Free** :- 99.75 MB

## Disk
 
- **/** :- Used: 44.51%
    - **Total** :- 3.81 GB
     - **Used** :- 1.7 GB
     - **Free** :- 1.94 GB
- **/boot** :- Used: 51.69%
    - **Total** :- 42.52 MB
     - **Used** :- 21.98 MB
     - **Free** :- 20.54 MB
- **/home/pi/data** :- Used: 1.33%
    - **Total** :- 10.35 GB
     - **Used** :- 140.92 MB
     - **Free** :- 9.69 GB

## HTTP
 
- **Server** :- Apache/2.4.25 (Raspbian) HTTP/1.1 CGI/1.1 80

## MySQL
 
- **Version** :- 5.5.5-10.1.23-MariaDB-9+deb9u1
- **Host** :- localhost:6379 (127.0.0.1)
- **Date** :- 2019-11-03 22:37:00 (UTC 00:00‌​)
- **Stats** :- Uptime: 6167142  Threads: 2  Questions: 60860  Slow queries: 0  Opens: 64  Flush tables: 1  Open tables: 40  Queries per second avg: 0.009

## Redis
 
- **Version** :- 3.2.6
- **Host** :- localhost:6379
- **Size** :- 463 keys (800.06K)
- **Uptime** :- 71 days

## MQTT Server
 
- **Version** :- Mosquitto 1.4.10
- **Host** :- localhost:1883 (127.0.0.1)

## PHP
 
- **Version** :- 7.0.30-0+deb9u1 (Zend Version 3.0.0)
- **Modules** :- apache2handler | calendar v7.0.30-0+deb9u1 | Core v7.0.30-0+deb9u1 | ctype v7.0.30-0+deb9u1 | curl v7.0.30-0+deb9u1 | date v7.0.30-0+deb9u1 | dom v20031129 | exif v7.0.30-0+deb9u1 | fileinfo v1.0.5 | filter v7.0.30-0+deb9u1 | ftp v7.0.30-0+deb9u1 | gd v7.0.30-0+deb9u1 | gettext v7.0.30-0+deb9u1 | hash v1.0 | iconv v7.0.30-0+deb9u1 | igbinary v2.0.1 | json v1.4.0 | libxml v7.0.30-0+deb9u1 | mbstring v7.0.30-0+deb9u1 | mcrypt v7.0.30-0+deb9u1 | mosquitto v0.4.0 | mysqli v7.0.30-0+deb9u1 | mysqlnd vmysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ | openssl v7.0.30-0+deb9u1 | pcre v7.0.30-0+deb9u1 | PDO v7.0.30-0+deb9u1 | pdo_mysql v7.0.30-0+deb9u1 | Phar v2.0.2 | posix v7.0.30-0+deb9u1 | readline v7.0.30-0+deb9u1 | redis v4.1.1 | Reflection v7.0.30-0+deb9u1 | session v7.0.30-0+deb9u1 | shmop v7.0.30-0+deb9u1 | SimpleXML v7.0.30-0+deb9u1 | sockets v7.0.30-0+deb9u1 | SPL v7.0.30-0+deb9u1 | standard v7.0.30-0+deb9u1 | sysvmsg v7.0.30-0+deb9u1 | sysvsem v7.0.30-0+deb9u1 | sysvshm v7.0.30-0+deb9u1 | tokenizer v7.0.30-0+deb9u1 | wddx v7.0.30-0+deb9u1 | xml v7.0.30-0+deb9u1 | xmlreader v7.0.30-0+deb9u1 | xmlwriter v7.0.30-0+deb9u1 | xsl v7.0.30-0+deb9u1 | Zend OPcache v7.0.30-0+deb9u1 | zlib v7.0.30-0+deb9u1

## Pi
 
- **Model** :- Raspberry Pi 3 Model B+ Rev 1.3 - 1GB (Sony UK)
- **SoC** :- Broadcom BCM2835
- **Serial num.** :- B4C03494
- **Temperature** :- 56.38°C - 56.9°C
- **emonpiRelease** :- emonSD-30Oct18
- **File-system** :- read-write
</details>

<details><summary>Client Information</summary>

# Client Information
## HTTP
 
- **Browser** :- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
- **Language** :- en-US,en;q=0.9

## Window
 
- **Size** :- 1903 x 937

## Screen
 
- **Resolution** :- 1920 x 1080
</details>

**Comment by borpin** [comment]
If you still have the issue, can you screenshot the error message please.
