### ISSUE TITLE
User permissions are hardcoded

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#57]
These scripts rely too heavily on hardcoded paths and assume the 'pi' user.

When installed on a different system (such as ubuntu) with a different username, the various scripts fail (import for instance) because of this.

**Comment by TrystanLea** [comment]
Thanks @borpin Fixed the places I can find that that hardcode to user pi:
https://github.com/emoncms/backup/commit/c62c5ab377f14f53a91ea529167d397049e9d1a6

**Comment by borpin** [comment]
Except you hardcoded the install location...

**Comment by borpin** [comment]
https://github.com/emoncms/backup/blob/e8110759c46a62aaa86f70756c169465ac7acf16/emoncms-copy.sh#L9
