### ISSUE TITLE
Apache error logs

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#58]
The following errors are seen in the Apache logs when the backup page is selected.

```
cat: /var/log/emoncms/exportbackup.log: No such file or directory
cat: /var/log/emoncms/exportbackup.log: No such file or directory
cat: /var/log/emoncms/usbimport.log: No such file or directory
```

**Comment by TrystanLea** [comment]
Thanks @borpin I've added checks for these: https://github.com/emoncms/backup/commit/9e42d84d1c2077238cddb1a03a5d62829b1101d2
