### ISSUE TITLE
Check if a config file already exists

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#65]
A check needs to be done to not overwrite an existing config file.

https://github.com/emoncms/backup/blob/ad179f8da8d62cf354427ddd3c05d2c415dffdb8/install.sh#L39-L42

**Comment by ArnyminerZ** [comment]
The check is in fact done [here](https://github.com/emoncms/backup/blob/master/install.sh#L36)

**Comment by borpin** [comment]
> The check is in fact done [here](https://github.com/emoncms/backup/blob/master/install.sh#L36)

This was added after my issue :(

I'll close it.
