### ISSUE TITLE
backup module no longer backs up old emonpi images

### ISSUE THREAD

**Issue by NeilW** [emoncms/backup#7]
=== Emoncms export start ===
Tue Jan  2 14:47:27 UTC 2018
EUID: 1000
Reading /home/pi/backup/config.cfg....
Location of mysql database: /home/pi/data
Location of emonhub.conf: /home/pi/data
Location of emoncms.conf: /home/pi/data
Location of Emoncms: /var/www/emoncms
Backup destination: /home/pi/data
old image
Log is turned off
Stopping feedwriter: stopped
Emoncms MYSQL database dump complete, adding files to archive ..
tar: Removing leading '/' from member names
tar: /home/pi/data/node-red/flows_emonpi.json: Cannot stat: No such file or directory
tar: /home/pi/data/node-red/flows_emonpi_cred.json: Cannot stat: No such file or directory
tar: /home/pi/data/node-red/settings.js: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Error: failed to tar config data
emoncms export failed

**Comment by glynhudson** [comment]
Thanks for letting me know, this should now be fixed. Please update to latest backup module version V1.1.1 by running emonPi update or git pull then try again. The issue was the backup module was trying to backup nodered when nodered does not exist on the old image. This has now been fixed. Thanks
